add *.out in .gitignore
pjbear1215/fork_vs_vfork pull request #1
Opened 2022-03-26 14:29 UTC by jwpark-sungshin

exclude *.out from git

resolved: TEST-1234

2022-03-26 14:58 UTC, pjbear1215 requested changes
This is looking great. I've left a few comments that should be addressed before this gets merged.

2022-03-26 14:58 UTC, pjbear1215 commented on .gitignore
> +*.out
```suggestion
*.out
*.o
*.exe
```

2022-03-27 00:12 UTC, jwpark-sungshin commented on .gitignore
> +*.out
OK.

2022-03-27 00:21 UTC, pjbear1215 approved these changes
Well done!

2022-03-27 00:24 UTC, closed without merging